### ISSUE TITLE
Non-empty CIGAR for unmapped reads

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#16]
1. cramtools usually correctly removes any alignment info (mapq, md:z:, nm:i: etc) for reads that don't align (flag &4), however I see a small number of reads where cramtools sets the cigar string to 76M. My data set is paired 76+76

**Comment by peterjc** [comment]
This is done deliberately in SAM/BAM for the special case of an embedded reference genome - see the spec in github (not yet on the website).

**Comment by vadimzalunin** [comment]
A non-issue then?

**Comment by peterjc** [comment]
Well, embedded references are a special case where they are flagged as unread but to have a CIGAR string that should be preserved (particularly for padded/gapped references - again see latest spec in repository). However CRAM probably has another mechanism for storing the reference, right?

I am unsure off hand if there are any other legitimate reasons to have a non-empty CIGAR string for an unmapped read - we're best asking on the samtools-devel list.

**Comment by vadimzalunin** [comment]
Currently there is no support for embedded references in CRAM. 
I have enforced a SAMRecord.NO_ALIGNMENT_CIGAR for all unmapped reads.This should appear in the next minor push.
