### ISSUE TITLE
Please retag v0.7 in github

### ISSUE THREAD

**Issue by peterjc** [vadimzalunin/crammer#18]
A tag on the commit 93e9ce00ca2bfe3233160b7ded872a8649fbb0e1 would include the version number fix,
https://github.com/vadimzalunin/crammer/commit/93e9ce00ca2bfe3233160b7ded872a8649fbb0e1

The existing old 0.7 tag lacks this and the update to the README file,
https://github.com/vadimzalunin/crammer/commit/d212079e3a497a3f29cfbd2ebc583b25c99f31cf

This is important for anyone using the tags with git at the command line, or via github to download v0.7

(You might choose to add a new tag, e.g. v0.7fixed, and leave the existing tag in situ - removing it or replacing it may cause warnings from git).

**Comment by vadimzalunin** [comment]
Done. I will also create v0.7 branch soon. 

Thanks!
