### ISSUE TITLE
Preserve everything from BAM header

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#19]
Some optional values are not preserved in 0.7, for example 
@RG     ID:SRR098401    PL:illumina     PU:ILLUMINA      LB:Solexa-51024 SM:NA12878      CN:bi

becomes 
@RG     ID:SRR098401    SM:NA12878

**Comment by peterjc** [comment]
Link to mailing list thread: http://listserver.ebi.ac.uk/pipermail/cram-dev/2012-March/000069.html

**Comment by vadimzalunin** [comment]
fixed in 0.8
