### ISSUE TITLE
Template length is off by 1

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#20]
$ samtools view
NA12878.mapped.illumina.mosaik.CEU.exome.20110411.chr20.bam
20:64000-65000 | cut -f -9
SRR098401.102568768 147 20  63932   64  76M =   63912   -95
SRR098401.7377046   99  20  63987   65  76M =   64163   251
SRR098401.48777644  83  20  64005   65  76M =   63864   -216
SRR098401.9345685   163 20  64010   56  76M =   64099   164

$ samtools view
NA12878.mapped.illumina.mosaik.CEU.exome.20110411.chr20.bam.cram.bam
20:64000-65000 | cut -f -9
146 147 20  63932   64  76M =   63912   -96
149 99  20  63987   65  76M =   64163   252
144 83  20  64005   65  76M =   63864   -217
151 163 20  64010   56  76M =   64099   165

This comes from the Picard's routine but I'm not sure how to fix this and who is right.

**Comment by peterjc** [comment]
Link to mailing list thread: http://listserver.ebi.ac.uk/pipermail/cram-dev/2012-March/000075.html

What happens if you look at the CRAM file directly? What TLEN does it say? That should tell you if the problem is in BAM to CRAM, or CRAM to BAM.

**Comment by vadimzalunin** [comment]
TLEN is not stored in CRAM, instead the value is calculated by Picard when converting CRAM to BAM.

**Comment by peterjc** [comment]
Might be a question for Tim Fennell, this thread from Jan 2012 looks relevant - there was/is a known issue in Picard with TLEN,
http://sourceforge.net/mailarchive/message.php?msg_id=28656712

**Comment by vadimzalunin** [comment]
Cramtools now uses Picard 1.66. At this point I'd say if this bug still exists it is not related to cramtools.
