### ISSUE TITLE
Hard Clipped Alignments

### ISSUE THREAD

**Issue by jtb** [vadimzalunin/crammer#21]
Are there any plans to allow Hard clippings (cigar operator H) in the CRAM format?  Is there a technical reason as to why it is not supported?

thanks,
Justin

**Comment by vadimzalunin** [comment]
It was excluded from original specs because CRAM was meant to be lossy format and hard clips have been also excluded from the ArchiveBAM specs (http://www.ebi.ac.uk/ena/about/archive_bam_format_1_0). 
We may need to think about hard clips again, it is not difficult to implement. May I ask why do you need hard clips preserved?

**Comment by jtb** [comment]
Thanks for the quick reply Vadim.  We use Novoalign with hard-clipping of low quality 3' bases turned on and adapter trimming turned on, so we get a bunch of hard clips in the alignments.  I don't see much need to keep that information around, although I guess it would be nice to have a lossless compression mode, at least until there is a general consensus that it is okay to start losing some information.  I was curious to see how much savings one would get with just the trick of using an auxiliary reference file while still preserving all the information.

Even if the CRAM format doesn't store hard clipping, I think it would be a nice if the BAM to CRAM conversion could accept BAM files with hard clips, and remove the hard clip operation for you with a warning that they have been removed - as opposed to getting an error or having to manually remove the hard clip operation before the conversion.

thanks again,
Justin

**Comment by vadimzalunin** [comment]
In the new version (0.8 just released) hard clips are ignored.
