### ISSUE TITLE
Duplicate fields in BAM header

### ISSUE THREAD

**Issue by johnbrox** [vadimzalunin/crammer#26]
I'm seeing duplicate fields in the un-crammed BAM header, in both the SQ lines (in the data1example; see below) as well as RG and PG lines in my own data.

samtools view -H /path/to/data/set1/input.bam
@SQ SN:1    LN:250000

java -jar/path/to/cramtools.jar cram --input-bam-file/path/to/data/set1/input.bam --reference-fasta-file /path/to/data/set1/ref.fa --output-cram-file set1.cram --capture-insertion-quality-scores --capture-substitution-quality-scores --capture-unmapped-quality-scores
java -jar /path/to/cramtools.jar bam --input-cram-file set1.cram --output-bam-file set1.cram.bam --reference-fasta-file /path/to/data/set1/ref.fa

samtools view -H set1.cram.bam
The tag 'LN' present (at least) twice on line [@SQ  SN:1    LN:250000   LN:250000   SN:1]
The tag 'SN' present (at least) twice on line [@SQ  SN:1    LN:250000   LN:250000   SN:1]
@HD VN:1.0  SO:coordinate
@SQ SN:1    LN:250000   LN:250000   SN:1

In @RG and @PG lines, only the ID field is duplicated.

Thanks
John

**Comment by vadimzalunin** [comment]
Oops, my fault. I'll post a fix tomorrow.
