### ISSUE TITLE
––capture–all–tags does produce almost empty cram files

### ISSUE THREAD

**Issue by maarten-k** [vadimzalunin/crammer#31]
When I ran cramtools with the --capture-all-tags something unexpected happened

> java -jar cramtools.jar cram --input-bam-file test.bam --reference-fasta-file /hg19/hg19_ordered.fa  ––capture–all–tags  --output-cram-file out.5.cram
> echo $?
> 0

 The process run in a split  second and the resulting cram file is 2294 bytes big. The orginal bam file is 2 Gb+ big.

When converted back to bam format, samtools view does not show any lines with default setting.

Other operations on the bam file with cramtools worked well.

**Comment by vadimzalunin** [comment]
Could you please check if there are mapped reads in the file? By default '--include-unmapped-reads' option is false, which could explain the symptoms.

**Comment by maarten-k** [comment]
Thanks for the quick reply!

According samtools their are reads:

> samtools flagstat test.bam
> 12561930 + 0 in total (QC-passed reads + QC-failed reads)
> 1132562 + 0 duplicates
> 11893429 + 0 mapped (94.68%:-nan%)
> 0 + 0 paired in sequencing
> 0 + 0 read1
> 0 + 0 read2
> 0 + 0 properly paired (-nan%:-nan%)
> 0 + 0 with itself and mate mapped
> 0 + 0 singletons (-nan%:-nan%)
> 0 + 0 with mate mapped to a different chr
> 0 + 0 with mate mapped to a different chr (mapQ>=5)

I included also --include-unmapped-reads option: this gives the same result

> time java -jar cramtools.jar cram --input-bam-file testl.bam --reference-fasta-file /hg19/hg19_ordered.fa  ––capture–all–tags --include-unmapped-reads  --output-cram-file out.5.cram
> real    0m1.612s
> user    0m0.288s
> sys     0m0.032s

**Comment by vadimzalunin** [comment]
Can you do one more thing? Try to get some reads using index: 
samtools view test.bam chr1:1-250000000 | head

You may want to replace 'chr1' with an entry from the bam file header. 

If that works fine (you can see some reads), would it be possible to share the file (or a part of it)?

**Comment by maarten-k** [comment]
I will send you a mail with the output.

**Comment by vadimzalunin** [comment]
A typo in the command.
