### ISSUE TITLE
CRAM record bit flags should be related to BAM bit flags.

### ISSUE THREAD

**Issue by vadimzalunin** [vadimzalunin/crammer#67]
CRAM records.You list "bit flags (see above)", but this should be expanded to BAM bit flags followed by CRAM bit flags. The latter are explained later, but should be moved to earlier in the spec.

**Comment by vadimzalunin** [comment]
specs updated

**Comment by jmarshall** [comment]
Is the updated spec available publicly anywhere?  e.g. I notice that the CRAM format 1.0.1.pdf in the source tree is not being updated along with these various spec updates.

**Comment by vadimzalunin** [comment]
This is for the next version, miliestone 1.1. It will be announced shortly.
